window.THINKING_TOOL_VIDEO = {
  meta: {
    id: "narrative-audit",
    duration: 246,
    seriesTitle: "PRACTICAL THINKING TOOLS",
    episodeLabel: "EP01 / NARRATIVE",
    themeBadge: "叙事审计",
  },
  hero: {
    eyebrow: "01 · NARRATIVE AUDIT",
    windowLabel: "audit-desk / fact vs story",
    headline: ["你以为是事实", "其实是故事"],
    strike: "今天不教你讲故事，教你拆故事。",
    subline: "让你持续行动的，往往不是事实本身，而是你接受了谁给你的解释。",
    metrics: [
      { label: "FACT", value: "事实" },
      { label: "STORY", value: "解释" },
      { label: "ACTION", value: "行动" },
    ],
  },
  principle: {
    number: "TOOL / 叙事审计",
    label: "把抽象叙事变成三栏工具",
    title: ["先拆事实", "再拆故事"],
    copy: "叙事审计，就是把一件事拆成：事实是什么、现在是谁在解释、这个解释把我推向什么行动。",
    footer: "FACT → STORY → ACTION",
    links: [
      { label: "OLD", title: "默认误判", body: "我痛苦，是因为事实本身太糟。" },
      { label: "NEW", title: "新的判断", body: "我先审计故事，再决定要不要按它行动。" },
    ],
  },
  caseStudy: {
    kicker: "CASE FILE",
    title: "同一组事实，两种行动",
    leftLabel: "旧叙事",
    leftMeta: "继续忍",
    oldStoryBadge: { label: "LABEL", value: "成长", score: "4M" },
    leftFlow: ["关键期成长", "我抗压差", "继续接会议", "代价算自己头上"],
    rightLabel: "审计后",
    rightMeta: "换行动",
    auditStamp: { stamp: "AUDIT" },
    rightFlow: ["事实先落表", "故事再贴标签", "行动后果写清", "边界开始可谈"],
    insight: "故事一旦写成“成长”，行动就会变成忍耐；故事被审计后，下一步才重新打开。",
  },
  diagnosis: {
    kicker: "THREE-COLUMN AUDIT",
    title: "把故事摊开",
    cards: [
      {
        index: "01",
        title: "事实是什么",
        body: "只写可观察、可验证的东西，不写解释。",
      },
      {
        index: "02",
        title: "现在的故事是什么",
        body: "这件事被谁命名成什么？它暗含了什么因果？",
      },
      {
        index: "03",
        title: "它让我继续做什么",
        body: "如果只让你忍、怕、讨好，就该重新审计。",
      },
    ],
  },
  action: {
    kicker: "TODAY'S AUDIT",
    title: "今天写三栏",
    items: [
      "选一件最近不舒服的事",
      "写下事实、故事、行动",
      "问：这故事是谁写给我的？",
    ],
    caption: "好叙事不是更好听，而是更接近事实，也更能让你看清下一步。",
  },
  outro: {
    kicker: "MEMORY LINE",
    line1: "让你行动的",
    line2: "不是事实",
    line3: "是你相信的故事",
    footer: "最近哪件事，是别人替你写的故事？",
  },
  captions: [
    { start: 0.6, end: 6.2, text: "你以为让你难受的是事实。" },
    { start: 6.2, end: 12.5, text: "但真正压住你的，可能是你接受了某个故事。" },
    { start: 12.5, end: 18.2, text: "今天不教你讲故事，我们来学拆故事。" },
    { start: 18.2, end: 26.0, text: "这叫叙事审计：先把事实和解释分开。" },
    { start: 26.0, end: 35.0, text: "你不是被事实困住，你可能是被某个叙事困住。" },
    { start: 38.0, end: 45.0, text: "叙事，就是把一串事实连起来的解释。" },
    { start: 45.0, end: 52.5, text: "同样是加班，有人说成长，有人说被低价消耗。" },
    { start: 52.5, end: 62.5, text: "事实可能一样，但故事不同，下一步就不同。" },
    { start: 62.5, end: 76.0, text: "叙事不只是让你好受一点，它会决定你继续做什么。" },
    { start: 80.0, end: 88.5, text: "林薇，31 岁，产品经理，业务连续四个月改方向。" },
    { start: 88.5, end: 99.0, text: "晚上十点后的会议越来越多，周末也经常临时拉群。" },
    { start: 99.0, end: 108.5, text: "公司叫它关键期成长，她自己也说：可能是我抗压差。" },
    { start: 108.5, end: 119.0, text: "于是她继续接会议、继续沉默、继续把身体变差当成不够强。" },
    { start: 119.0, end: 132.0, text: "事实只有几条：会议变多、方向反复、身体变差。" },
    { start: 132.0, end: 145.0, text: "但故事一旦写成成长，她的行动就被安排好了。" },
    { start: 148.0, end: 156.0, text: "第一步，只写事实，不写解释。" },
    { start: 156.0, end: 164.0, text: "第二步，写当前叙事：这件事被谁命名成什么？" },
    { start: 164.0, end: 173.0, text: "第三步，写行动后果：这个故事让我继续做什么？" },
    { start: 173.0, end: 182.5, text: "到这里，故事就露出来了。它是一条行动指令。" },
    { start: 182.5, end: 195.0, text: "最后，写一个更接近事实、也更能保护行动的替代叙事。" },
    { start: 198.0, end: 205.0, text: "选一件最近让你不舒服的事。" },
    { start: 205.0, end: 213.0, text: "先别急着解决，写三栏。" },
    { start: 213.0, end: 222.0, text: "事实是什么？现在的故事是什么？它正在让我做什么？" },
    { start: 222.0, end: 229.0, text: "如果它只让你忍、怕、讨好，就该问一句。" },
    { start: 231.0, end: 237.0, text: "叙事不是谎言，它是你和世界交互的接口。" },
    { start: 237.0, end: 245.0, text: "让你行动的不是事实，是你相信的故事。" },
  ],
  timing: {
    heroStart: 0,
    heroEnd: 36,
    principleStart: 36.1,
    principleEnd: 78,
    caseStart: 78.1,
    caseRightReveal: 116,
    caseInsightReveal: 134,
    caseEnd: 146,
    diagnosisStart: 146.1,
    diagnosisEnd: 196,
    actionStart: 196.1,
    actionEnd: 230,
    outroStart: 230.1,
    outroEnd: 246,
  },
};
