window.NAVAL_VIDEO = {
  meta: {
    id: "naval-sell-build-v4",
    duration: 105.4,
  },
  hero: {
    eyebrow: "THE NAVAL PRINCIPLE · 04",
    headline: ["两周产品", "0 付费"],
    strike: "问题可能不在构建",
    subline: "你以为还要加功能，但可能是还没有验证真实需求。",
    metrics: [
      { label: "BUILD TIME", value: "14 DAYS" },
      { label: "VISITS", value: "17" },
      { label: "PAID", value: "0" },
    ],
  },
  principle: {
    number: "LEARN TO SELL. LEARN TO BUILD.",
    label: "纳瓦尔说，要学会销售，也要学会构建",
    title: ["销售发现真实需求", "构建兑现真实承诺"],
    copy: "只会其中一个，你都只拥有半条价值链。",
    links: [
      { label: "SELL", title: "发现需求", body: "确认谁真的愿意为问题付出代价。" },
      { label: "BUILD", title: "兑现承诺", body: "把已经被验证的答案交付出来。" },
    ],
  },
  caseStudy: {
    kicker: "CASE FILE · XIAOLIN",
    title: "同一个简历诊断产品，两条路径",
    leftLabel: "只会构建",
    leftMeta: "继续开发",
    leftFlow: ["AI 模型", "评分图表", "17 个访问", "0 个付费"],
    rightLabel: "销售 + 构建",
    rightMeta: "先卖问题",
    rightFlow: ["飞书表单", "20 个访谈", "99 元人工诊断", "10 单后产品化"],
    insight: "差距不在谁更会包装，而在谁先确认别人愿意为问题付出代价。",
  },
  diagnosis: {
    kicker: "DIAGNOSIS",
    title: "不要先问还能加什么",
    cards: [
      {
        index: "01",
        title: "先找人群",
        body: "谁正在被这个问题卡住？",
      },
      {
        index: "02",
        title: "再问代价",
        body: "他们付出了时间、钱，还是机会成本？",
      },
      {
        index: "03",
        title: "最后才加功能",
        body: "没有真实回答前，新增功能只是逃回舒适区。",
      },
    ],
  },
  action: {
    kicker: "TODAY'S TEST",
    title: "今天只做一个小动作",
    items: [
      "列 10 个可能有痛点的人",
      "联系其中 3 个",
      "问上一次付出了什么",
    ],
    caption: "在得到真实回答前：不新增功能，不买课，不重做作品集。",
  },
  outro: {
    kicker: "MEMORY LINE",
    line1: "只会做，是产能",
    line2: "只会卖，是承诺",
    line3: "能卖也能做，才是资产",
    footer: "你做的东西，已经有人付出代价了吗？",
  },
  captions: [
    { start: 0.2, end: 2.6, text: "你做了两周产品，最后零个付费。" },
    { start: 2.6, end: 4.4, text: "你会以为，是功能不够强。" },
    { start: 4.4, end: 7.1, text: "于是调模型、改页面、加图表。" },
    { start: 7.1, end: 9.0, text: "但问题可能不在构建。" },
    { start: 9.0, end: 10.7, text: "而在你没有销售。" },
    { start: 11.0, end: 12.9, text: "销售不是忽悠买单。" },
    { start: 12.9, end: 14.8, text: "它是发现真实需求。" },
    { start: 14.8, end: 17.3, text: "构建也不是躲起来做功能。" },
    { start: 17.3, end: 20.2, text: "它是兑现真实承诺。" },
    { start: 20.7, end: 24.5, text: "纳瓦尔说，要学会销售，也要学会构建。" },
    { start: 24.5, end: 26.4, text: "因为只会其中一个。" },
    { start: 26.4, end: 29.2, text: "你都只拥有半条价值链。" },
    { start: 30.8, end: 32.8, text: "小林，二十九岁工程师。" },
    { start: 32.8, end: 35.5, text: "他用 AI 做了一个简历诊断产品。" },
    { start: 35.5, end: 38.5, text: "两周上线，有评分、有建议、有图表。" },
    { start: 38.5, end: 40.7, text: "结果只有十七个访问。" },
    { start: 40.7, end: 42.1, text: "零个付费。" },
    { start: 42.5, end: 44.2, text: "他以为功能不够。" },
    { start: 44.2, end: 45.8, text: "于是继续开发。" },
    { start: 46.1, end: 48.3, text: "但他的同事先没写代码。" },
    { start: 48.3, end: 50.1, text: "只做了一个飞书表单。" },
    { start: 50.1, end: 53.0, text: "他约了二十个求职者聊简历。" },
    { start: 53.0, end: 55.6, text: "收九十九元，做人工诊断。" },
    { start: 55.6, end: 57.3, text: "先卖出十单。" },
    { start: 57.3, end: 60.2, text: "再把三类高频问题产品化。" },
    { start: 60.7, end: 63.0, text: "差距不在谁更会包装。" },
    { start: 63.0, end: 64.6, text: "而在谁先确认。" },
    { start: 64.6, end: 67.3, text: "别人愿意为问题付出代价。" },
    { start: 67.8, end: 69.4, text: "小林会构建。" },
    { start: 69.4, end: 71.1, text: "但还没有销售。" },
    { start: 71.1, end: 72.8, text: "同事先卖问题。" },
    { start: 72.8, end: 74.7, text: "再构建答案。" },
    { start: 75.0, end: 76.4, text: "所以，别急着问。" },
    { start: 76.4, end: 78.0, text: "我还能加什么功能。" },
    { start: 78.2, end: 80.4, text: "先问，谁正为它付出时间、钱。" },
    { start: 80.4, end: 82.0, text: "或者机会成本。" },
    { start: 82.3, end: 83.5, text: "今天就做一个小动作。" },
    { start: 83.5, end: 84.9, text: "选一个你已经会的能力。" },
    { start: 84.9, end: 86.6, text: "写下十个可能有痛点的人。" },
    { start: 86.6, end: 87.7, text: "联系其中三个。" },
    { start: 87.7, end: 89.4, text: "问他们上一次付出了什么。" },
    { start: 89.6, end: 92.7, text: "在得到真实回答前，不新增功能，不买课，不重做作品集。" },
    { start: 93.0, end: 97.4, text: "只会做，是产能；只会卖，是承诺；能卖也能做，才是资产。" },
    { start: 97.4, end: 105.2, text: "你现在做的东西，已经有人为它付出代价了吗？" },
  ],
  timing: {
    heroStart: 0,
    heroEnd: 20.5,
    principleStart: 20.6,
    principleEnd: 31.0,
    caseStart: 31.1,
    caseRightReveal: 46.0,
    caseInsightReveal: 60.4,
    caseEnd: 75.0,
    diagnosisStart: 75.1,
    diagnosisEnd: 82.1,
    actionStart: 82.2,
    actionEnd: 92.9,
    outroStart: 93.0,
    outroEnd: 105.4,
  },
};
