window.NAVAL_VIDEO = {
  meta: {
    id: "naval-longterm-v4",
    duration: 85.8,
  },
  hero: {
    eyebrow: "THE NAVAL PRINCIPLE · 01",
    headline: ["别把努力", "放在短期游戏里"],
    strike: "真正的复利，先让你看起来很慢",
    subline: "短期游戏消耗精力，长期游戏积累身份、信任和判断。",
  },
  caseStudy: {
    kicker: "A THREE-YEAR CASE",
    title: "同样努力，三年后差在哪",
    leftLabel: "追短期反馈",
    leftFlow: ["追热点", "换方向", "重新开始", "继续焦虑"],
    rightLabel: "玩长期游戏",
    rightFlow: ["选窄问题", "持续交付", "复盘判断", "积累信任"],
    insight: "三年后，差距不在谁更忙，而在谁的每次努力都能留下复利。",
  },
  principle: {
    number: "LONG-TERM GAMES",
    label: "纳瓦尔说，和长期的人玩长期游戏",
    title: ["短期游戏赢热闹", "长期游戏赢自由"],
    copy: "长期主义不是忍耐，而是把努力放在一个会累积身份、能力和信任的系统里。",
  },
  pillars: {
    kicker: "MAKE TIME WORK FOR YOU",
    title: "让时间站到你这边",
    cards: [
      {
        index: "01",
        title: "选一个长期问题",
        body: "不是选最热的方向，而是选一个你愿意研究三年、十年的真实问题。",
      },
      {
        index: "02",
        title: "持续交付",
        body: "作品、产品、代码、文章，都要能被别人反复看到、使用和信任。",
      },
      {
        index: "03",
        title: "固定复盘",
        body: "每周记录一次：我判断对了什么，错在哪，下次怎么改。",
      },
    ],
  },
  action: {
    kicker: "7-DAY COMPOUNDING TEST",
    title: "这周做一次长期主义实验",
    items: [
      "删掉一个只追短期反馈的动作",
      "选一个愿意投入三年的窄问题",
      "连续七天交付一个小作品或小判断",
    ],
    caption: "别问怎样更快赢，先问什么东西值得你一直赢。",
  },
  outro: {
    kicker: "MEMORY LINE",
    line1: "短期努力",
    line2: "让你变忙",
    line3: "长期复利，让你变贵",
    footer: "Naval Almanack · Long-term games compound.",
  },
  captions: [
    { start: 0.1, end: 5.12, text: "很多人不是不努力，而是把努力放在了太短的游戏里。" },
    { start: 5.07, end: 10.14, text: "今天学一个技巧，明天追一个风口，后天又换一个方向。" },
    { start: 10.14, end: 17.49, text: "看起来很忙，但每一次都在重新开始。纳瓦尔说，和长期的人玩长期游戏。" },
    { start: 17.49, end: 23.67, text: "真正的复利，不是突然爆发，而是时间开始站在你这边。" },
    { start: 23.67, end: 31.11, text: "比如两个创作者，都想做知识内容。一个人每天追热点，什么火就讲什么。" },
    { start: 31.11, end: 38.07, text: "另一个人只研究一个窄问题，持续写、持续讲、持续复盘自己的判断。" },
    { start: 38.07, end: 46.6, text: "第一年，前者看起来更热闹。第三年，后者开始拥有稳定的信任、案例和方法。" },
    { start: 46.6, end: 52.21, text: "差距不在谁更忙，而在谁的每一次努力都能留下资产。" },
    { start: 52.21, end: 58.99, text: "所以长期主义不是忍耐，也不是鸡汤。它是选择一个会累积的游戏。" },
    { start: 58.99, end: 65.04, text: "你不是在等一个结果，而是在建设一个会越来越信任你的系统。" },
    { start: 65.04, end: 76.54, text: "这周做一个小实验：删掉一个只追短期反馈的动作。选一个愿意投入三年的问题，连续七天交付一个小作品或小判断。" },
    { start: 76.54, end: 85.67, text: "把它留下来，而不是做完就丢掉。短期努力让你变忙，长期复利让你变贵。" },
  ],
  timing: {
    heroStart: 0,
    heroEnd: 17.4,
    principleStart: 17.6,
    principleEnd: 23.6,
    caseStart: 23.8,
    caseEnd: 52.2,
    pillarsStart: 52.4,
    pillarsEnd: 65.0,
    actionStart: 65.2,
    actionEnd: 80.0,
    outroStart: 80.2,
    outroEnd: 85.8,
  },
};
