window.NAVAL_VIDEO = {
  meta: {
    id: "naval-leverage-v4",
    duration: 89.2,
  },
  hero: {
    eyebrow: "THE NAVAL PRINCIPLE · 02",
    headline: ["别再只靠", "工时赚钱"],
    strike: "努力要先接上放大器",
    subline: "没有杠杆，努力只能线性增长；有杠杆，判断会被系统复制。",
  },
  caseStudy: {
    kicker: "A WORK VS ASSET CASE",
    title: "同样工作，差距在哪",
    leftLabel: "卖时间",
    leftFlow: ["接需求", "交付一次", "停止就归零", "继续接单"],
    rightLabel: "建杠杆",
    rightFlow: ["发现重复问题", "做成资产", "反复分发", "系统运行"],
    insight: "真正的差距不是工作时长，而是有没有把一次判断变成可重复分发的资产。",
  },
  principle: {
    number: "LEVERAGE",
    label: "纳瓦尔说，财富来自杠杆",
    title: ["杠杆不是偷懒", "是让判断可复制"],
    copy: "团队和资本需要许可，但代码、内容和产品，是普通人今天就能启动的无许可杠杆。",
  },
  pillars: {
    kicker: "PERMISSIONLESS LEVERAGE",
    title: "普通人先建这三种杠杆",
    cards: [
      {
        index: "01",
        title: "代码",
        body: "把重复劳动写进程序，让它在你不在线时继续运行。",
      },
      {
        index: "02",
        title: "内容",
        body: "把一次判断做成文章、视频、播客，让它被反复看见。",
      },
      {
        index: "03",
        title: "产品",
        body: "把经验封装成工具、模板或服务，让交付不再只靠你本人。",
      },
    ],
  },
  action: {
    kicker: "7-DAY LEVERAGE TEST",
    title: "这周做一个小杠杆",
    items: [
      "找一个你反复回答或反复做的事情",
      "把它做成模板、脚本、清单或内容",
      "发出去，让它替你工作七天",
    ],
    caption: "别只问怎么更努力，先问努力能不能被复制。",
  },
  outro: {
    kicker: "MEMORY LINE",
    line1: "卖时间",
    line2: "只能加法增长",
    line3: "建杠杆，才有乘法结果",
    footer: "Naval Almanack · Leverage multiplies judgment.",
  },
  captions: [
    { start: 0.1, end: 4.23, text: "如果你赚钱只靠工时，你的上限其实很低。" },
    { start: 4.18, end: 10.15, text: "因为一天只有二十四小时，而且你停下来，收入也会停下来。" },
    { start: 10.15, end: 18.15, text: "纳瓦尔说，财富来自杠杆。杠杆不是偷懒，而是让一次正确判断被系统复制。" },
    { start: 18.15, end: 26.97, text: "比如两个自由职业者，都很专业。一个人每次都从接需求开始，交付一次，收一次钱。" },
    { start: 26.97, end: 35.48, text: "另一个人发现客户总问同一类问题，于是做成模板、文章、脚本，甚至一个小产品。" },
    { start: 35.48, end: 44.09, text: "前者停止工作就归零。后者睡觉时，内容和工具还在帮他筛选客户、建立信任。" },
    { start: 44.09, end: 50.94, text: "这就是杠杆。团队和资本也能放大结果，但它们通常需要许可。" },
    { start: 50.94, end: 58.11, text: "普通人更容易启动的，是代码、内容和产品。它们不需要谁批准你开始。" },
    { start: 58.11, end: 64.25, text: "如果这件事只能由你本人重复，它就不是杠杆，只是更忙。" },
    { start: 64.25, end: 78.33, text: "这周做一个小实验：找一个你反复回答、反复操作、反复解释的事情。把它做成模板、脚本、清单或一条内容。" },
    { start: 78.33, end: 89.14, text: "发出去，让它替你工作七天。你要做的，是让一次判断被很多人、很多次使用。建杠杆才有乘法结果。" },
  ],
  timing: {
    heroStart: 0,
    heroEnd: 18.0,
    principleStart: 18.2,
    principleEnd: 26.8,
    caseStart: 27.0,
    caseEnd: 44.0,
    pillarsStart: 44.2,
    pillarsEnd: 64.0,
    actionStart: 64.2,
    actionEnd: 83.0,
    outroStart: 83.2,
    outroEnd: 89.2,
  },
};
