window.NAVAL_VIDEO = {
  meta: {
    id: "naval-retirement-time-audit-v1",
    duration: 100.788,
  },
  hero: {
    eyebrow: "TIME DEBT REPORT · EP05",
    headline: ["你真的想", "退休吗？"],
    strike: "不是不工作，是停止被迫工作",
    subline: "周日夜的消息不是小事，是今天被明天抵押的证据。",
    metrics: [
      { label: "SUNDAY", value: "22:47" },
      { label: "WORK PINGS", value: "+12" },
      { label: "FULL DAY", value: "缺席" },
    ],
  },
  principle: {
    number: "RETIREMENT IS NOT A DATE.",
    label: "纳瓦尔提醒：退休不是未来节点",
    title: ["不是某个日期", "是今天完整"],
    copy: "当你不再为了明天反复抵押今天，退休才开始有现实含义。",
    links: [
      { label: "旧判断", title: "年龄或存款", body: "45 岁、一笔钱、某个日期，被当成未来救援点。" },
      { label: "新判断", title: "今天是否完整", body: "日历、晚餐、作品时间，没有被未来持续拿走。" },
    ],
  },
  caseStudy: {
    kicker: "CASE FILE · TIME DEBT",
    title: "时间债务诊断：抵押 vs 边界",
    leftLabel: "阿宁",
    leftMeta: "运营负责人",
    leftFlow: ["周末消息持续弹出", "23:00 还在改方案", "晚餐常常空掉", "作品时间归零"],
    rightLabel: "同事",
    rightMeta: "时间账单",
    rightFlow: ["36 小时低价值消耗", "会议块被移除", "19:00 后不可约", "周五上午作品时间"],
    insight: "他没有停止工作，只是从日历里拿回了一小块选择权。",
  },
  diagnosis: {
    kicker: "DIAGNOSIS",
    title: "你不是讨厌劳动",
    cards: [
      {
        index: "01",
        title: "不是懒",
        body: "是完整的一天被低价值响应切碎。",
      },
      {
        index: "02",
        title: "不是想逃",
        body: "是想停止被迫工作，重新拥有边界。",
      },
      {
        index: "03",
        title: "不是等未来",
        body: "是今天先少抵押一点。",
      },
    ],
  },
  action: {
    kicker: "RETIREMENT AUDIT",
    title: "这周只审一件事",
    items: [
      "写下 3 件让你不想过星期一的事",
      "选 1 件正在抵押今天的事",
      "删掉 / 定价 / 委托 / 重新谈边界",
    ],
    caption: "不用立刻改变人生，先拿回一小块今天。",
  },
  outro: {
    kicker: "MEMORY LINE",
    line1: "真正的退休",
    line2: "不是不工作",
    line3: "是今天不再被明天绑架",
    footer: "你这周，最想先拿回哪一块时间？",
  },
  captions: [
    { start: 0.00, end: 2.08, text: "你说，等我退休就好了。" },
    { start: 2.08, end: 4.35, text: "但你可能不是想停止工作。" },
    { start: 4.35, end: 6.43, text: "你只是想停止被迫工作。" },
    { start: 6.49, end: 9.01, text: "很多人把退休想成一个年龄。" },
    { start: 9.01, end: 10.37, text: "比如四十五岁。" },
    { start: 10.37, end: 12.50, text: "或者一笔终于够用的钱。" },
    { start: 12.50, end: 14.44, text: "纳瓦尔的提醒更直接。" },
    { start: 14.44, end: 16.19, text: "退休不是某个日期。" },
    { start: 16.19, end: 18.13, text: "是今天本身已经完整。" },
    { start: 18.13, end: 21.04, text: "你不再为了明天，反复抵押今天。" },
    { start: 21.10, end: 24.00, text: "阿宁，三十四岁，做运营负责人。" },
    { start: 24.00, end: 25.94, text: "她计划四十五岁退休。" },
    { start: 25.94, end: 28.46, text: "每个月存下百分之六十工资。" },
    { start: 28.46, end: 29.82, text: "听起来很清醒。" },
    { start: 29.82, end: 32.92, text: "但她连续六个月，周末都在回消息。" },
    { start: 32.92, end: 35.25, text: "晚上十一点，还在改方案。" },
    { start: 35.25, end: 37.77, text: "她的日历上，晚餐常常空掉。" },
    { start: 37.77, end: 40.29, text: "想做的作品，一直没有开始。" },
    { start: 40.29, end: 42.23, text: "问题不是她不够努力。" },
    { start: 42.23, end: 46.10, text: "问题是她把今天，交给了未来那个自由版本。" },
    { start: 46.16, end: 47.88, text: "她的同事没有裸辞。" },
    { start: 47.88, end: 49.97, text: "也没有说我要提前退休。" },
    { start: 49.97, end: 52.06, text: "他先做了一张时间账单。" },
    { start: 52.06, end: 53.58, text: "一周三十六小时。" },
    { start: 53.58, end: 56.43, text: "都耗在低价值会议和即时响应里。" },
    { start: 56.43, end: 58.91, text: "于是他先砍掉两个固定会议。" },
    { start: 58.91, end: 61.19, text: "把晚上七点后设成不可约。" },
    { start: 61.19, end: 64.42, text: "周五上午，只留给一个能积累的项目。" },
    { start: 64.42, end: 66.52, text: "注意，他没有停止工作。" },
    { start: 66.52, end: 68.99, text: "他只是拿回了一小块选择权。" },
    { start: 69.05, end: 70.95, text: "所以，想退休这句话。" },
    { start: 70.95, end: 72.85, text: "有时候不是讨厌劳动。" },
    { start: 72.85, end: 75.31, text: "是你太久没有过完整的一天。" },
    { start: 75.31, end: 77.21, text: "你不一定想停止工作。" },
    { start: 77.21, end: 79.68, text: "你可能只是想停止被迫工作。" },
    { start: 79.74, end: 81.86, text: "今天就做一次退休审计。" },
    { start: 81.86, end: 84.76, text: "写下三件让你不想过星期一的事。" },
    { start: 84.76, end: 85.92, text: "选其中一件。" },
    { start: 85.92, end: 89.97, text: "这周试着删掉、定价、委托，或者重新谈边界。" },
    { start: 89.97, end: 91.71, text: "不用立刻改变人生。" },
    { start: 91.71, end: 93.45, text: "先拿回一小块今天。" },
    { start: 93.45, end: 95.77, text: "真正的退休，不是不工作。" },
    { start: 95.77, end: 97.89, text: "是今天不再被明天绑架。" },
    { start: 97.89, end: 100.79, text: "你这周，最想先拿回哪一块时间？" },
  ],
  timing: {
    heroStart: 0,
    heroEnd: 6.43,
    principleStart: 6.49,
    principleEnd: 21.04,
    caseStart: 21.10,
    caseRightReveal: 46.16,
    caseInsightReveal: 64.42,
    caseEnd: 68.99,
    diagnosisStart: 69.05,
    diagnosisEnd: 79.68,
    actionStart: 79.74,
    actionEnd: 93.45,
    outroStart: 93.45,
    outroEnd: 100.788,
  },
};
