window.NAVAL_VIDEO = {
  meta: {
    id: "naval-topic-template",
    duration: 90,
    seriesTitle: "NAVAL ALMANACK",
    episodeLabel: "EPXX / TOPIC",
    themeBadge: "NAVAL PRINCIPLE",
  },
  hero: {
    eyebrow: "THE NAVAL PRINCIPLE · EPXX",
    windowLabel: "case-file / diagnosis report",
    headline: ["现实冲突", "反常识判断"],
    strike: "先写本集要纠正的误判",
    subline: "用一句具体的话说明：观众为什么现在需要停下来听。",
    metrics: [
      { label: "PAIN", value: "具体痛点" },
      { label: "COST", value: "真实代价" },
      { label: "ACTION", value: "当天动作" },
    ],
  },
  principle: {
    number: "ONE PRINCIPLE",
    label: "把纳瓦尔原则改写成一句现实判断",
    title: ["旧判断", "新判断"],
    copy: "这里写清楚：本集不是解释概念，而是替观众换掉一个判断。",
    footer: "OLD BELIEF → NEW JUDGMENT",
    links: [
      { label: "OLD", title: "默认误判", body: "观众通常怎么想。" },
      { label: "NEW", title: "新的判断", body: "这条视频希望观众怎么想。" },
    ],
  },
  caseStudy: {
    kicker: "CASE FILE",
    title: "同一个问题，两条路径",
    leftLabel: "旧路径",
    leftMeta: "继续消耗",
    leftMock: { label: "SIGNAL", value: "v1", score: "?" },
    leftFlow: ["默认做法", "重复消耗", "代价累积", "没有资产"],
    rightLabel: "新路径",
    rightMeta: "改变一个动作",
    rightMock: { stamp: "NEXT MOVE" },
    rightFlow: ["先做审计", "找到关键代价", "处理一件事", "拿回选择权"],
    insight: "差距不在懂不懂道理，而在有没有把判断落成一个动作。",
  },
  diagnosis: {
    kicker: "DIAGNOSIS",
    title: "不要先问我懂了什么",
    cards: [
      {
        index: "01",
        title: "先找误判",
        body: "观众当前把问题看错在哪里？",
      },
      {
        index: "02",
        title: "再找代价",
        body: "这个误判正在拿走什么？",
      },
      {
        index: "03",
        title: "最后给动作",
        body: "本周能处理哪一件小事？",
      },
    ],
  },
  action: {
    kicker: "TODAY'S AUDIT",
    title: "今天只做一个小动作",
    items: [
      "写下 3 个具体问题",
      "选其中 1 个",
      "本周删掉、定价、委托或谈边界",
    ],
    caption: "行动要小到今天能开始，具体到画面能呈现。",
  },
  outro: {
    kicker: "MEMORY LINE",
    line1: "这里写第一句记忆句",
    line2: "这里写第二句记忆句",
    line3: "这里写最终落点",
    footer: "用一个轻问题促评论，不要喊口号。",
  },
  captions: [
    { start: 0.2, end: 2.6, text: "第一句先说出观众的真实心声。" },
    { start: 2.6, end: 5.2, text: "第二句立刻给出反常识判断。" },
    { start: 5.2, end: 8.0, text: "第三句说明这条视频要纠正什么。" },
    { start: 9.0, end: 13.0, text: "把纳瓦尔原则改写成一句现实判断。" },
    { start: 13.0, end: 18.0, text: "不要做书摘，要解决一个当下焦虑。" },
    { start: 20.0, end: 27.0, text: "用具体人物、场景、动作和代价证明判断。" },
    { start: 27.0, end: 36.0, text: "数字必须有来源，动作必须能被画面接住。" },
    { start: 38.0, end: 48.0, text: "给出对照路径，避免观众把主题误解成另一个方向。" },
    { start: 50.0, end: 58.0, text: "把案例压成一句能自我代入的诊断。" },
    { start: 60.0, end: 74.0, text: "给一个今天或七天内能做的小动作。" },
    { start: 75.0, end: 86.0, text: "用记忆句收束，让观众能转述这条判断。" },
  ],
  timing: {
    heroStart: 0,
    heroEnd: 18,
    principleStart: 18.1,
    principleEnd: 30,
    caseStart: 30.1,
    caseRightReveal: 42,
    caseInsightReveal: 54,
    caseEnd: 62,
    diagnosisStart: 62.1,
    diagnosisEnd: 72,
    actionStart: 72.1,
    actionEnd: 82,
    outroStart: 82.1,
    outroEnd: 90,
  },
};
