window.NAVAL_VIDEO = {
  meta: {
    id: "naval-specific-knowledge-v4",
    duration: 105.4,
  },
  hero: {
    eyebrow: "THE NAVAL PRINCIPLE · 03",
    headline: ["AI 时代", "别只会通用技能"],
    strike: "最先变便宜的，是可复制能力",
    subline: "工具越强，“我会做”越不稀缺；真正稀缺的是判断。",
  },
  caseStudy: {
    kicker: "A REAL AI-AGE CASE",
    title: "同样会用 AI，差距在哪",
    leftLabel: "会调用工具",
    leftFlow: ["丢需求", "拿结果", "交付", "结束"],
    rightLabel: "能定义问题",
    rightFlow: ["判断价值", "识别边界", "验证结果", "沉淀流程"],
    insight: "几个月后，差距不在速度，而在别人复制不了的问题解决系统。",
  },
  principle: {
    number: "SPECIFIC KNOWLEDGE",
    label: "纳瓦尔说，真正值钱的是具体知识",
    title: ["通用技能只是入场券", "具体知识让你稀缺"],
    copy: "它不是刷几门课就能复制的，而是兴趣、经历、性格和长期试错混成的判断。",
  },
  pillars: {
    kicker: "TURN EXPERIENCE INTO AN ASSET",
    title: "把经验变成资产",
    cards: [
      {
        index: "01",
        title: "选一个窄问题",
        body: "别泛泛地学，先锁定一个你反复遇到、也愿意长期研究的问题。",
      },
      {
        index: "02",
        title: "记录判断和坑",
        body: "每天记下一个判断、一个错误边界、一个你下次会怎么改。",
      },
      {
        index: "03",
        title: "做成可复用物",
        body: "第七天，把它整理成文章、清单、脚本或小工具。",
      },
    ],
  },
  action: {
    kicker: "7-DAY EXPERIMENT",
    title: "这周就做一个实验",
    items: [
      "选一个反复遇到的小问题",
      "每天记录一个判断、一个坑、一个改进",
      "第七天做成文章、清单、脚本或小工具",
    ],
    caption: "别只问还要学什么，先问你能沉淀什么。",
  },
  outro: {
    kicker: "MEMORY LINE",
    line1: "通用技能",
    line2: "让你跟上时代",
    line3: "具体知识，让时代离不开你",
    footer: "Naval Almanack · Specific knowledge compounds.",
  },
  captions: [
    { start: 0.1, end: 7.98, text: "AI 出来以后，最先变便宜的，不是能力差的人，而是只会通用技能的人。" },
    { start: 7.98, end: 13.43, text: "你会写代码，他也会。你会写文案，他也会。" },
    { start: 13.43, end: 26.28, text: "当工具把基础能力批量放大以后，真正值钱的东西会往后移：从“我会做”，移到“我知道什么值得做”。" },
    { start: 26.28, end: 33.35, text: "这就是纳瓦尔说的具体知识。它不是学校统一教出来的，也不是刷几门课就能复制的。" },
    { start: 33.35, end: 40.55, text: "它来自你的兴趣、经历、性格，还有长期试错。举个更现实的例子。" },
    { start: 40.55, end: 50.89, text: "两个开发者，都会用 AI 写代码。一个人把需求丢给工具，拿到结果，交付，然后结束。" },
    { start: 50.89, end: 64.66, text: "另一个人会先问：这个需求到底解决什么问题？哪些边界最容易出错？怎么验证结果可靠？" },
    { start: 64.66, end: 72.49, text: "几个月以后，前者只是更快地完成任务，后者开始拥有别人很难复制的问题解决系统。" },
    { start: 72.49, end: 81.6, text: "所以，别只问自己还要学什么。你要问：我能在哪个小领域，持续积累判断？" },
    { start: 81.6, end: 91, text: "这周就做一个七天实验。选一个你反复遇到的问题，每天记录一个判断、一个坑、一个改进。" },
    { start: 91, end: 99, text: "第七天，把它整理成一篇文章、一个清单、一个脚本，或者一个小工具。" },
    { start: 99, end: 105.28, text: "通用技能让你跟上时代。具体知识，才让时代离不开你。" },
  ],
  timing: {
    heroStart: 0,
    heroEnd: 13.3,
    principleStart: 13.5,
    principleEnd: 40.3,
    caseStart: 40.5,
    caseEnd: 72.4,
    pillarsStart: 72.6,
    pillarsEnd: 83.2,
    actionStart: 83.4,
    actionEnd: 99,
    outroStart: 99.1,
    outroEnd: 105.4,
  },
};
